Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'lib/letsencryptor/aws_route53/client.rb'

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable